#!/bin/bash
s="util/init_context.go
service/init.go
ngap/handler.go
ngap/message/send_test.go.test
ngap/message/send_test.go.test
ngap/message/send_test.go.test
producer/n1n2message.go
producer/callback.go
producer/callback.go
consumer/ue_authentication.go
consumer/sm_context.go
consumer/communication.go
gmm/sm.go
gmm/sm.go
gmm/handler.go
gmm/handler.go
gmm/handler.go
gmm/handler.go
gmm/handler.go
gmm/message/send.go
gmm/message/send.go
gmm/message/build.go
gmm/message/build.go
gmm/message/build.go
gmm/message/build.go
context/amf_ue.go
context/amf_ue.go
context/amf_ue.go
context/sm_context.go
nas/nas_security/security.go
nas/nas_security/security.go
nas/dispatch.go"
for f in $s
do
    sed -i 's#github.com/free5gc/nas#github.com/nycu-ucr/nas#g' $f
done
