#!/bin/bash
s="./util/search_nf_service.go
./util/convert.go
./util/init_context.go
./oam/api_registered_ue_context.go
./oam/api_registered_ue_context.go
./mt/api_ue_context_document.go
./mt/api_ue_context_document.go
./eventexposure/api_individual_subscription_document.go
./eventexposure/api_individual_subscription_document.go
./eventexposure/api_subscriptions_collection_document.go
./eventexposure/api_subscriptions_collection_document.go
./service/init.go
./service/init.go
./ngap/handler.go
./ngap/message/send.go
./ngap/message/build.go
./ngap/message/send_test.go.test
./ngap/message/forward_ie.go
./factory/config.go
./producer/n1n2message.go
./producer/subscription.go
./producer/oam.go
./producer/location_info.go
./producer/mt.go
./producer/callback/n1n2message.go
./producer/callback/n1n2message.go
./producer/callback/subscription.go
./producer/callback/subscription.go
./producer/callback/ue_context.go
./producer/callback/ue_context.go
./producer/callback.go
./producer/ue_context.go
./producer/event_exposure.go
./consumer/am_policy.go
./consumer/am_policy.go
./consumer/am_policy.go
./consumer/nf_mangement.go
./consumer/nf_mangement.go
./consumer/nf_mangement.go
./consumer/ue_context_management.go
./consumer/ue_context_management.go
./consumer/ue_context_management.go
./consumer/nsselection.go
./consumer/nsselection.go
./consumer/nsselection.go
./consumer/subscriber_data_management.go
./consumer/subscriber_data_management.go
./consumer/subscriber_data_management.go
./consumer/nf_discovery.go
./consumer/nf_discovery.go
./consumer/ue_authentication.go
./consumer/ue_authentication.go
./consumer/ue_authentication.go
./consumer/sm_context.go
./consumer/sm_context.go
./consumer/sm_context.go
./consumer/sm_context.go
./consumer/communication.go
./consumer/communication.go
./consumer/communication.go
./gmm/sm.go
./gmm/handler.go
./gmm/handler.go
./gmm/handler.go
./gmm/message/send.go
./gmm/message/build.go
./httpcallback/api_n1_message_notify.go
./httpcallback/api_n1_message_notify.go
./httpcallback/api_am_policy_control_update_notify.go
./httpcallback/api_am_policy_control_update_notify.go
./httpcallback/api_sm_context_status_notify.go
./httpcallback/api_sm_context_status_notify.go
./context/common_function.go
./context/context.go
./context/3gpp_types.go
./context/amf_ue.go
./context/amf_ran.go
./context/sm_context.go
./context/ran_ue.go
./communication/api_individual_subscription_document.go
./communication/api_individual_subscription_document.go
./communication/api_n1_n2_message_collection_document.go
./communication/api_n1_n2_message_collection_document.go
./communication/api_n1_n2_individual_subscription_document.go
./communication/api_n1_n2_individual_subscription_document.go
./communication/api_individual_ue_context_document.go
./communication/api_individual_ue_context_document.go
./communication/api_n1_n2_subscriptions_collection_for_individual_ue_contexts_document.go
./communication/api_n1_n2_subscriptions_collection_for_individual_ue_contexts_document.go
./communication/api_subscriptions_collection_document.go
./communication/api_subscriptions_collection_document.go
./nas/nas_security/security.go
./nas/dispatch.go
./location/api_individual_ue_context_document.go
./location/api_individual_ue_context_document.go"
for f in $s
do
    sed -i 's#github.com/free5gc/openapi#github.com/nycu-ucr/openapi#g' $f
done
